window.__SEVENTHRELIC__ = {
  "images": [
    "assets/images/posts/post1/bros for life.jpg",
    "assets/images/posts/post1/me and you against the world.jpg",
    "assets/images/posts/post1/we gonna make it.jpg",
    "assets/images/posts/post2/ignore the haters get rich.jpg",
    "assets/images/posts/post2/no excuses just results.jpg",
    "assets/images/posts/post2/you have time be great.jpg",
    "assets/images/posts/post3/life is beautiful smile.jpg",
    "assets/images/posts/post3/life is better outside.jpg",
    "assets/images/posts/post3/never stop being real.jpg",
    "assets/images/posts/post4/dont forget to chill.jpg",
    "assets/images/posts/post4/make yourself proud.jpg",
    "assets/images/posts/post4/never stop hustlin.jpg",
    "assets/images/posts/post5/comfort never built greatness.jpg",
    "assets/images/posts/post5/consistency creates confidence.jpg",
    "assets/images/posts/post5/discipline will always win.jpg",
    "assets/images/posts/post6/dream big perform bigger.jpg",
    "assets/images/posts/post6/greatness is a choide.jpg",
    "assets/images/posts/post6/train until winning is a habit.jpg",
    "assets/images/posts/post7/bet on yourself.jpg",
    "assets/images/posts/post7/destined for more.jpg",
    "assets/images/posts/post7/some ppl wait for opportunities.jpg",
    "assets/images/posts/post8/be yourself always.jpg",
    "assets/images/posts/post8/embrace the chaos.jpg",
    "assets/images/posts/post8/stay goofy twin.jpg",
    "assets/images/posts/post9/just keep livin.jpg",
    "assets/images/posts/post9/nothing is that serious.jpg",
    "assets/images/posts/post9/who cares what others think.jpg",
    "assets/images/posts/post10/IMG_7056.jpeg",
    "assets/images/posts/post10/IMG_7057.jpeg",
    "assets/images/posts/post10/IMG_7058.jpeg",
    "assets/images/posts/post10/good things take time.jpg",
    "assets/images/posts/post10/trust the process.jpg",
    "assets/images/posts/post10/your moment is coming.jpg",
    "assets/images/posts/post11/fall hard, rise harder.jpg",
    "assets/images/posts/post11/never stop fighting.jpg",
    "assets/images/posts/post11/your story isnt over.jpg",
    "assets/images/posts/post12/great things take courage.jpg",
    "assets/images/posts/post12/no sacrifice no success.jpg",
    "assets/images/posts/post12/started with a dream.jpg",
    "assets/images/posts/post13/comfort feels good.jpg",
    "assets/images/posts/post13/follow your own path.jpg",
    "assets/images/posts/post13/it is what it is.jpg",
    "assets/images/posts/post14/just take the leap.jpg",
    "assets/images/posts/post14/the hardest step is the first.jpg",
    "assets/images/posts/post14/you dont have to do it alone.jpg",
    "assets/images/posts/post15/master your craft.jpg",
    "assets/images/posts/post15/obsession beats talent.jpg",
    "assets/images/posts/post15/stop when youre perfect.jpg",
    "assets/images/posts/post16/dreams require sacrifice.jpg",
    "assets/images/posts/post16/future.jpg",
    "assets/images/posts/post16/history remembers the bold.jpg",
    "assets/images/posts/post17/earn your legacy.jpg",
    "assets/images/posts/post17/i stop when i win.jpg",
    "assets/images/posts/post17/the harder you work.jpg",
    "assets/images/posts/post18/built by ambition.jpg",
    "assets/images/posts/post18/every setback is a step forward.jpg",
    "assets/images/posts/post18/stay focused.jpg",
    "assets/images/posts/post19/still i rise.jpg",
    "assets/images/posts/post19/why not you.jpg",
    "assets/images/posts/post19/you dont become great overnight.jpg",
    "assets/images/posts/post20/built different.jpg",
    "assets/images/posts/post20/i have results.jpg",
    "assets/images/posts/post20/keep doubting me.jpg",
    "assets/images/posts/post21/become unforgettable.jpg",
    "assets/images/posts/post21/stay true to who you are.jpg",
    "assets/images/posts/post21/the only thing between you is action.jpg",
    "assets/images/posts/post22/become inevitable.jpg",
    "assets/images/posts/post22/do the impossible.jpg",
    "assets/images/posts/post22/this is only the beginning.jpg",
    "assets/images/posts/post23/earn your honour.jpg",
    "assets/images/posts/post23/the journey matters more.jpg",
    "assets/images/posts/post23/your legacy is built by your actions.jpg",
    "assets/images/posts/post24/IMG_7237.jpeg",
    "assets/images/posts/post24/IMG_7238.jpeg",
    "assets/images/posts/post24/IMG_7239.jpeg",
    "assets/images/posts/post25/choose kindness.jpg",
    "assets/images/posts/post25/the world needs good people.jpg",
    "assets/images/posts/post25/the choices make us who we are.jpg",
    "assets/images/posts/post26/dreams dont work unless you do.jpg",
    "assets/images/posts/post26/if not now then when.jpg",
    "assets/images/posts/post26/risk is always better than regret.jpg"
  ]
};

/* Added post25 and post26 images */
// window.__SEVENTHRELIC__.images.push(

// );
